# Generated by Django 5.2.6 on 2025-09-20 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
