version: "3.9"

services:
  web:
    build: .
    container_name: messaging_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/messaging_project
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: messaging_db
    environment:
      POSTGRES_DB: messaging_db
      POSTGRES_USER: chika
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
